spring.application.name=faturamento-core

# ==========================================
# CONFIGURAÇÕES DO SERVIDOR
# ==========================================
server.port=8080
server.servlet.context-path=/api

# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS (POSTGRESQL)
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ==========================================
# update: Atualiza o banco automaticamente com as novas entidades (ótimo para desenvolvimento)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURAÇÕES EXTRA (JWT SECRET)
# ==========================================
api.security.token.secret=${JWT_SECRET}